spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb  
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true 
    ip-address: ${INSTANCE_IP:localhost}
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${HOSTNAME:unknown}:${server.port}
