server:
  port: 8761  # Стандартный порт Eureka

spring:
  application:
    name: discovery-service  # Имя сервиса (для Config Server и логирования)

# Настройки Eureka Server
eureka:
  instance:
    hostname: discovery-service  # Должен совпадать с именем в Docker
    prefer-ip-address: false     # Не использовать IP (важно для Docker)
  client:
    register-with-eureka: false  # Не регистрировать себя в Eureka
    fetch-registry: false        # Не загружать реестр (если нет кластера)
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false  # Отключить для тестов (в prod — true)
    eviction-interval-timer-in-ms: 5000  # Частота очистки мертвых инстансов (5 сек)

# Health-чек для Docker
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
