server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888  # Сделать запрос опциональным
  
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service  # Используем имя сервиса из Eureka
          predicates:
            - Path=/api/orders/**
    config:
      fail-fast: true  # Остановиться если Config Server недоступен
      retry:
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 10

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service1:8761/eureka/
    register-with-eureka: true  # Явное указание
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
