server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://config-service:8888"  # Критически важная строка
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
    config:
      fail-fast: false  # Изменили на false для большей устойчивости
      retry:
        initial-interval: 5000
        max-interval: 15000
        max-attempts: 10

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service1:8761
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
