server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: configserver:http://config-service:8888  # Ключевая строка!
  
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service  # Используем имя сервиса из Eureka
          predicates:
            - Path=/api/orders/**
    config:
    request-read-timeout: 10000 # 10 секунд
      request-connect-timeout: 5000 # 5 секунд
      fail-fast: true  # Остановиться если Config Server недоступен

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/  # Исправляем localhost на имя сервиса

management:
  endpoints:
    web:
      exposure:
        include: "*"
