
spring:
  application:
    name: ticketService
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true 
    ip-address: ${INSTANCE_IP:localhost}
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${HOSTNAME:unknown}:${server.port}
